name: Micro Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push header MFE
        run: |
          cd mfes/header
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-header:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-header:latest

      - name: Build and push home MFE
        run: |
          cd mfes/home
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-home:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-home:latest

      - name: Build and push info_page MFE
        run: |
          cd mfes/info_page
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-info_page:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-info_page:latest

      - name: Build and push review_page MFE
        run: |
          cd mfes/review_page
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-review_page:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-review_page:latest

      - name: Build and push search_result MFE
        run: |
          cd mfes/search_result
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-search_result:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-search_result:latest

      - name: Build and push watchlist MFE
        run: |
          cd mfes/watchlist
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-watchlist:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-watchlist:latest

      - name: Build and push host MFE
        run: |
          cd mfes/host
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mfe-host:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mfe-host:latest